### ISSUE TITLE
'Invalid Swift Support' While resign both language (objective,swift) code app with your software.

### ISSUE THREAD

**Issue by PGandhi30** [cjsliuj/Scalpel#1]
I resigned an IPA with your software and it will make resignable-IPA perfectly. I uploaded on app store via application loader and apple store throw an error in the mail. "Invalid Swift Support" swift support folder is missing.

My project code in a mixed language ( Objective - C, Swift). 

How to resign an app with your app?  What changes are required for resigning app?

**Comment by cjsliuj** [comment]
You'd better not use this tool to re-sign packages that you want to publish to the appstore.
You should use Xcode to generate the ipa that will be published to the App Store.
I have never tested whether a re-signed package can be released and the original intention of this tool is not for this. It just to be able to install on the test iDevice for testing after ipa modification.😂
